pipeline:
  publish:
    image: plugins/docker
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: justinbarrick/plexbot
    tags:
    - latest
    - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    when:
      branch: master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  helm_deploy:
    image: justinbarrick/drone-helm
    skip_tls_verify: true
    chart: ./helm
    release: plexbot
    values: image.tag=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7},plexbot.sonarr_token=$${SONARR_TOKEN},plexbot.couchpotato_token=$${COUCHPOTATO_TOKEN},plexbot.slack_client_id=$${SLACK_CLIENT_ID},plexbot.slack_client_secret=$${SLACK_CLIENT_SECRET}
    secrets: [ PROD_KUBERNETES_CERT, PROD_KUBERNETES_TOKEN, PROD_SERVICE_ACCOUNT, PROD_API_SERVER, PROD_SONARR_TOKEN, PROD_SLACK_CLIENT_ID, PROD_SLACK_CLIENT_SECRET, PROD_COUCHPOTATO_TOKEN, PROD_RADARR_TOKEN ]
    prefix: PROD
    wait: true
    when:
      branch: master

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: plex
    when:
      status: [success, failure]
