pipeline:
  git_push:
    image: appleboy/drone-git-push
    branch: master
    secrets: [ GIT_PUSH_SSH_KEY ]
    remote: ssh://git@deis-builder.codesink.net:2222/plexbot.git
    force: false

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: plex
    when:
      status: [success, failure]
