kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plexbot-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: {{ .Values.storageClass }}
